### ISSUE TITLE
Globals interferes with babel class-transform enabled features

### ISSUE THREAD

**Issue by KaySackey** [calvinmetcalf/rollup-plugin-node-globals#6]
Let's say that I have a file like such:

```javascript
class A {
    static hello = "world"; // roll up will fail here
    
    get current_view() {
        // process
    }
}

```

And compile it with:

```javascript
import nodeResolve from "rollup-plugin-node-resolve";
import globals from "rollup-plugin-node-globals";
import babel from "rollup-plugin-babel";

export default {
    entry  : "./rollup.test.js",
    dest   : "./bundle.js",
    plugins: [
        nodeResolve({
            browser       : true,
        }),
        globals(),
        babel({
            exclude: "node_modules/**",
            babelrc: false,
            presets: [
                [ "es2015-rollup"],  "stage-0"
            ],
            plugins: [
                "transform-decorators-legacy",
            ]
        }),
    ],
}
```

Rollup will fail saying:

```console
🚨   Unexpected token (2:17) in ~rollup.test.js
undefined (2:17)
```

If I remove rollup-plugin-node-globals or use another word than 'process' in the comment then it works.

I'm not sure why it's even triggering anything here because of a comment. Any thoughts on this?

This is as minimal as I could get the setup, but it seems to involve:

- rollup-plugin-node-globals does some kind of preprocessing
- babel running on any es2016/es2017 features that use the class transform will then fail. That is decorators or static properties.

Apart from that particular interaction, everything seems to work fine.

**Comment by calvinmetcalf** [comment]
so a couple different things are happening:

1. the reason the comment changes things is because we first do a string search to make sure node globals are actually present before trying to parse them, so since process is one we're looking for the comment tells us, hey we might have something here, hence why that's why it affects things.

2. you are using stage 0 features which can be described as JavaScript features somebody once had a dream about.  In other words they are *extremely* vague and tentative so most parsers do not support them, hence the error.  You can try just running the babel transform first.

**Comment by calvinmetcalf** [comment]
* correction you are using a draft level feature which is still not completely speced out and has the permanence of a sand castle so it's not something to expect in other parsers.

**Comment by KaySackey** [comment]
The thing that threw me was that process is simply in a comment, so when I modified the file to *not* include stage-2 features, then it'd output a bundle correctly, but:

1. Process would still be a comment
2. The additional code included by rollup-plugin-node-globals if you use something like process.env.NODE_ENV would not be included in the bundle.

----

I've gotten it to work by including it into the rollup configuration *after* babel.  This works for my purposes.

Thanks for the assistance.
